// samples/commerce-agent-chat/react/src/components/commerce/ComparisonSummary.tsx
import {useEffect, useRef} from 'react';

interface ComparisonSummaryElement extends HTMLElement {
  text: string;
}

interface ComparisonSummaryProps {
  text: string;
}

export function ComparisonSummary({text}: ComparisonSummaryProps) {
  const elementRef = useRef<ComparisonSummaryElement | null>(null);

  useEffect(() => {
    if (elementRef.current) {
      elementRef.current.text = text;
    }
  }, [text]);

  return <cac-comparison-summary ref={elementRef} />;
}

// samples/commerce-agent-chat/react-headless/src/components/ComparisonSummary.tsx
import './ComparisonSummary.css';

interface ComparisonSummaryProps {
  text: string;
}

export function ComparisonSummary({
  text,
}: ComparisonSummaryProps): React.JSX.Element | null {
  if (!text.trim()) {
    return null;
  }

  return (
    <div className="rh-comparison-summary">
      <p className="rh-comparison-summary__text">{text}</p>
    </div>
  );
}
