// samples/commerce-agent-chat/angular/src/app/components/message-input.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {FormsModule} from '@angular/forms';

@Component({
  selector: 'app-message-input',
  standalone: true,
  imports: [FormsModule],
  template: `
    <form
      class="message-form"
      (ngSubmit)="onSubmit()"
      aria-label="Send message"
    >
      <label for="chat-input" class="visually-hidden">Type your message</label>
      <p id="chat-input-hint" class="visually-hidden">
        Press Enter to send. Press Shift plus Enter to insert a new line.
      </p>
      <textarea
        id="chat-input"
        name="chatInput"
        class="message-input"
        [disabled]="disabled"
        [(ngModel)]="value"
        placeholder="Ask Zane..."
        rows="2"
        aria-describedby="chat-input-hint"
        (keydown)="onKeyDown($event)"
      ></textarea>
      <button
        type="submit"
        class="send-button"
        [disabled]="disabled || value.trim().length === 0"
      >
        Send
      </button>
    </form>
  `,
})
export class MessageInputComponent {
  @Input() disabled = false;
  @Output() send = new EventEmitter<string>();

  value = '';

  onKeyDown(event: KeyboardEvent): void {
    if (event.key !== 'Enter' || event.shiftKey) {
      return;
    }

    event.preventDefault();
    this.onSubmit();
  }

  onSubmit(): void {
    const content = this.value.trim();
    if (!content || this.disabled) {
      return;
    }

    this.send.emit(content);
    this.value = '';
  }
}

// samples/commerce-agent-chat/react-headless/src/components/MessageInput.tsx
import {useEffect, useId, useRef} from 'react';
import './MessageInput.css';

interface MessageInputProps {
  onSend: (message: string) => void;
  value: string;
  onValueChange: (value: string) => void;
  disabled: boolean;
  placeholder?: string;
  isClassifying?: boolean;
  shouldFocusInput?: boolean;
  onFocusHandled?: () => void;
  slot?: string;
  onGoToSearch?: () => void;
}

export function MessageInput({
  onSend,
  value,
  onValueChange,
  disabled,
  placeholder = 'Ask something...',
  isClassifying = false,
  shouldFocusInput = false,
  onFocusHandled,
  slot,
  onGoToSearch,
}: MessageInputProps): React.JSX.Element {
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);
  const inputId = useId();
  const inputHintId = `${inputId}-hint`;

  useEffect(() => {
    if (!shouldFocusInput) {
      return;
    }

    const frameId = requestAnimationFrame(() => {
      textareaRef.current?.focus();
      onFocusHandled?.();
    });

    return () => cancelAnimationFrame(frameId);
  }, [shouldFocusInput, onFocusHandled]);

  const isDisabled = disabled || isClassifying;
  const resolvedPlaceholder = isClassifying ? 'Classifying...' : placeholder;
  const isSubmitDisabled = isDisabled || value.trim().length === 0;

  const submitValue = () => {
    const content = value.trim();
    if (!content || isDisabled) {
      return;
    }
    onSend(content);
  };

  const onSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    submitValue();
  };

  const onKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.key !== 'Enter' || event.shiftKey) {
      return;
    }
    event.preventDefault();
    submitValue();
  };

  return (
    <div className="input-with-switch" slot={slot}>
      <form
        className="rh-message-input-form"
        aria-label="Send message"
        onSubmit={onSubmit}
      >
        <label className="visually-hidden" htmlFor={inputId}>
          Type your message
        </label>
        <p id={inputHintId} className="visually-hidden">
          Press Enter to send. Press Shift plus Enter to insert a new line.
        </p>
        <div className="rh-message-input-shell">
          <textarea
            ref={textareaRef}
            id={inputId}
            className="rh-message-input"
            value={value}
            disabled={isDisabled}
            placeholder={resolvedPlaceholder}
            rows={2}
            aria-describedby={inputHintId}
            onChange={(event) => onValueChange(event.currentTarget.value)}
            onKeyDown={onKeyDown}
          />
          <button
            className="rh-send-button"
            type="submit"
            disabled={isSubmitDisabled}
          >
            Send
          </button>
        </div>
      </form>
      {onGoToSearch && (
        <button
          type="button"
          className="go-search-btn"
          onClick={onGoToSearch}
          aria-label="Go to search"
          title="Go to search"
        >
          <span aria-hidden="true">🔍</span>
        </button>
      )}
    </div>
  );
}
