// samples/commerce-agent-chat/vue/src/components/commerce/ComparisonTable.vue
<script setup lang="ts">
import {formatAttribute} from '@core/lib/commerceHelpers.js';
import type {Product} from '@core/types/commerce.js';
import PriceDisplay from './PriceDisplay.vue';

defineProps<{
  heading: string;
  products: Product[];
  attributes?: string[];
  isLoading?: boolean;
}>();
</script>

<template>
  <div
    v-if="products.length === 0 && (isLoading ?? false)"
    class="comparison-table-wrap"
    aria-busy="true"
  >
    <h3 class="commerce-heading">{{ heading }}</h3>
    <div class="comparison-table-loading">
      <div class="comparison-table-loading__line" />
      <div
        class="comparison-table-loading__line comparison-table-loading__line--wide"
      />
      <div class="comparison-table-loading__grid">
        <div class="comparison-table-loading__cell" />
        <div class="comparison-table-loading__cell" />
        <div class="comparison-table-loading__cell" />
      </div>
    </div>
  </div>

  <div v-else-if="products.length > 0" class="comparison-table-wrap">
    <h3 class="commerce-heading">{{ heading }}</h3>
    <div class="comparison-table-scroll">
      <table class="comparison-table">
        <thead>
          <tr>
            <th class="comparison-table__attr-col">Attribute</th>
            <th v-for="product in products" :key="product.ec_product_id">
              {{ product.ec_name }}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="comparison-table__label">Image</td>
            <td
              v-for="product in products"
              :key="`${product.ec_product_id}-image`"
            >
              <img
                v-if="product.ec_image"
                :src="product.ec_image"
                :alt="product.ec_name"
                class="comparison-table__thumb"
              />
              <span v-else class="text-muted">No image</span>
            </td>
          </tr>
          <tr>
            <td class="comparison-table__label">Brand</td>
            <td
              v-for="product in products"
              :key="`${product.ec_product_id}-brand`"
            >
              {{ product.ec_brand }}
            </td>
          </tr>
          <tr>
            <td class="comparison-table__label">Price</td>
            <td
              v-for="product in products"
              :key="`${product.ec_product_id}-price`"
            >
              <PriceDisplay :product="product" />
            </td>
          </tr>
          <tr v-for="attribute in attributes ?? []" :key="attribute">
            <td class="comparison-table__label">
              {{ formatAttribute(attribute) }}
            </td>
            <td
              v-for="product in products"
              :key="`${product.ec_product_id}-${attribute}`"
            >
              <span v-if="product[attribute] != null">{{
                product[attribute]
              }}</span>
              <span v-else class="text-muted">—</span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<style scoped>
.comparison-table-wrap {
  display: flex;
  flex-direction: column;
  gap: 0.4rem;
}

.comparison-table-loading {
  border: 2px solid rgba(0, 212, 255, 0.2);
  border-radius: 10px;
  background: linear-gradient(
    135deg,
    rgba(22, 45, 66, 0.4) 0%,
    rgba(26, 58, 82, 0.3) 100%
  );
  padding: 0.85rem;
  display: grid;
  gap: 0.45rem;
  backdrop-filter: blur(5px);
}

.comparison-table-loading__line,
.comparison-table-loading__cell {
  border-radius: 6px;
  background: linear-gradient(
    90deg,
    rgba(26, 77, 109, 0.3) 25%,
    rgba(0, 212, 255, 0.15) 50%,
    rgba(26, 77, 109, 0.3) 75%
  );
  background-size: 600px 100%;
  animation: shimmer 1.4s infinite linear;
}

.comparison-table-scroll {
  overflow-x: auto;
}

.comparison-table {
  border-collapse: collapse;
  width: 100%;
  font-size: 0.82rem;
}

.comparison-table th,
.comparison-table td {
  padding: 0.55rem 0.8rem;
  border: 1px solid rgba(0, 212, 255, 0.2);
  text-align: left;
  vertical-align: middle;
  color: var(--ink);
}

.comparison-table thead th {
  background: rgba(26, 58, 82, 0.6);
  font-weight: 700;
  color: var(--accent);
  border-bottom: 2px solid rgba(0, 212, 255, 0.3);
}

.comparison-table__attr-col {
  min-width: 100px;
  background: rgba(26, 58, 82, 0.4);
  font-weight: 600;
}

.comparison-table__thumb {
  width: 48px;
  height: 48px;
  object-fit: cover;
  border-radius: 6px;
  border: 1px solid rgba(0, 212, 255, 0.2);
  display: block;
}

.text-muted {
  color: var(--ink-muted);
}
</style>

// samples/thermidor/generative-angular/src/app/components/comparison-table.component.ts
import {ChangeDetectionStrategy, Component, input} from '@angular/core';
import {ComparisonTableSurface} from '../models';

@Component({
  selector: 'app-comparison-table',
  template: `
    <section class="surface">
      <header class="surface-header">
        <p class="surface-kicker">Comparison Table</p>
        <h3>{{ surface().heading }}</h3>
      </header>

      @if (surface().isLoading || surface().products.length === 0) {
        <div class="loading-table"></div>
      } @else {
        <div class="product-strip">
          @for (product of surface().products; track product.ec_product_id) {
            <article class="product-card">
              @if (product.ec_image) {
                <img
                  class="product-image"
                  [src]="product.ec_image"
                  [alt]="product.ec_name"
                  loading="lazy"
                />
              } @else {
                <div class="product-image-placeholder"></div>
              }
              <div class="product-info">
                <span class="product-brand">{{ product.ec_brand }}</span>
                <strong class="product-name">{{ product.ec_name }}</strong>
                <span class="product-price">{{
                  formatPrice(product.ec_promo_price ?? product.ec_price)
                }}</span>
              </div>
            </article>
          }
        </div>

        <div class="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Product</th>
                @for (attribute of surface().attributes; track attribute) {
                  <th>{{ formatLabel(attribute) }}</th>
                }
                <th>Price</th>
              </tr>
            </thead>
            <tbody>
              @for (product of surface().products; track product.ec_product_id) {
                <tr>
                  <td>
                    <strong>{{ product.ec_name }}</strong>
                    <span>{{ product.ec_brand }}</span>
                  </td>
                  @for (attribute of surface().attributes; track attribute) {
                    <td>{{ product[attribute] || '—' }}</td>
                  }
                  <td>
                    {{ formatPrice(product.ec_promo_price ?? product.ec_price) }}
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      }
    </section>
  `,
  styles: [
    `
      .surface-header {
        margin-bottom: 16px;
      }

      .surface-kicker {
        margin: 0 0 6px;
        text-transform: uppercase;
        letter-spacing: 0.1em;
        font-size: 0.74rem;
        color: #516661;
      }

      h3 {
        margin: 0;
      }

      .table-wrap {
        overflow-x: auto;
        margin-top: 14px;
      }

      table {
        width: 100%;
        border-collapse: collapse;
        min-width: 560px;
      }

      th,
      td {
        padding: 12px 10px;
        border-bottom: 1px solid rgba(17, 35, 31, 0.12);
        text-align: left;
        vertical-align: top;
      }

      td span {
        display: block;
        margin-top: 4px;
        color: #516661;
        font-size: 0.92rem;
      }

      .product-strip {
        display: flex;
        gap: 14px;
        overflow-x: auto;
        scroll-snap-type: x mandatory;
        padding-bottom: 8px;
      }

      .product-card {
        flex: 0 0 200px;
        scroll-snap-align: start;
        border-radius: 18px;
        background: rgba(255, 255, 255, 0.8);
        border: 1px solid rgba(17, 35, 31, 0.08);
        overflow: hidden;
      }

      .product-image {
        width: 100%;
        height: 130px;
        object-fit: cover;
        background: #f0ece4;
      }

      .product-image-placeholder {
        width: 100%;
        height: 130px;
        background: linear-gradient(135deg, #e7d8c8, #c6a889);
      }

      .product-info {
        padding: 12px 14px;
        display: flex;
        flex-direction: column;
        gap: 4px;
      }

      .product-brand {
        text-transform: uppercase;
        letter-spacing: 0.08em;
        font-size: 0.7rem;
        color: #516661;
      }

      .product-name {
        font-size: 0.88rem;
      }

      .product-price {
        font-size: 0.85rem;
        font-weight: 600;
        color: #204f46;
      }

      .loading-table {
        height: 220px;
        border-radius: 18px;
        background: linear-gradient(
          90deg,
          rgba(231, 221, 209, 0.95),
          rgba(247, 241, 232, 0.95),
          rgba(231, 221, 209, 0.95)
        );
        background-size: 200% 100%;
        animation: shimmer 1.25s linear infinite;
      }

      @keyframes shimmer {
        0% {
          background-position: 200% 0;
        }
        100% {
          background-position: -200% 0;
        }
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ComparisonTableComponent {
  readonly surface = input.required<ComparisonTableSurface>();

  protected formatLabel(value: string): string {
    return value.replace(/_/g, ' ');
  }

  protected formatPrice(value: number): string {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
    }).format(value);
  }
}
