// samples/commerce-agent-chat/react-headless/src/App.tsx
import {useEffect, useState} from 'react';
import {
  createEngineControllers,
  loadEngineConfig,
  type EngineControllers,
} from './engine.js';
import {CommerceAgentInterface} from './components/CommerceAgentInterface.js';

export function App(): React.JSX.Element {
  const [controllers, setControllers] = useState<EngineControllers | null>(
    null
  );
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    try {
      const config = loadEngineConfig();
      const ctrl = createEngineControllers(config);
      setControllers(ctrl);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Configuration failed');
    }
  }, []);

  if (error) {
    return (
      <main className="state-screen" role="alert">
        <section className="state-card">
          <h1>Configuration Error</h1>
          <pre>{error}</pre>
        </section>
      </main>
    );
  }

  if (!controllers) {
    return (
      <main className="state-screen" aria-live="polite">
        <section className="state-card">Loading engine...</section>
      </main>
    );
  }

  return <CommerceAgentInterface controllers={controllers} />;
}

// samples/commerce-agent-chat/vue/src/App.vue
<script setup lang="ts">
import {ref} from 'vue';

import {loadConfig, type CommerceConfig} from '@core/config/env.js';

import ChatInterface from './components/ChatInterface.vue';

const config = ref<CommerceConfig | null>(null);
const error = ref<string | null>(null);

try {
  config.value = loadConfig();
} catch (err) {
  error.value = err instanceof Error ? err.message : 'Configuration failed';
}
</script>

<template>
  <main v-if="error" class="state-screen" role="alert">
    <section class="state-card">
      <h1>Configuration Error</h1>
      <pre>{{ error }}</pre>
    </section>
  </main>

  <main v-else-if="!config" class="state-screen" aria-live="polite">
    <section class="state-card">Loading configuration...</section>
  </main>

  <ChatInterface v-else :config="config" />
</template>
