// samples/thermidor/generative-angular/src/app/components/bundle-display.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  input,
  signal,
  computed,
} from '@angular/core';
import {BundleDisplaySurface} from '../models';

@Component({
  selector: 'app-bundle-display',
  template: `
    <section class="surface">
      <header class="surface-header">
        <p class="surface-kicker">Bundle Display</p>
        <h3>{{ surface().title }}</h3>
      </header>

      @if (surface().isLoading || surface().bundles.length === 0) {
        <div class="loading-grid">
          @for (item of placeholders; track $index) {
            <div class="loading-card"></div>
          }
        </div>
      } @else {
        <nav class="tier-tabs" role="tablist">
          @for (bundle of surface().bundles; track bundle.bundleId) {
            <button
              class="tier-tab"
              [class.active]="isActive(bundle.bundleId)"
              (click)="selectTier(bundle.bundleId)"
              type="button"
              role="tab"
              [attr.aria-selected]="isActive(bundle.bundleId)"
            >
              {{ bundle.label }}
            </button>
          }
        </nav>

        @if (activeTier(); as tier) {
          <p class="tier-description">{{ tier.description }}</p>

          <div class="slot-carousel">
            @for (
              slot of tier.slots;
              track slot.surfaceRef + ':' + slot.categoryLabel
            ) {
              <div class="slot-card">
                <span class="slot-label">{{ slot.categoryLabel }}</span>
                @if (slot.product) {
                  @if (slot.product.ec_image) {
                    <img
                      class="slot-image"
                      [src]="slot.product.ec_image"
                      [alt]="slot.product.ec_name"
                      loading="lazy"
                    />
                  }
                  <strong class="slot-name">{{ slot.product.ec_name }}</strong>
                  <small class="slot-brand">{{ slot.product.ec_brand }}</small>
                  @if (slot.product.ec_price) {
                    <span class="slot-price">{{
                      formatPrice(slot.product.ec_price)
                    }}</span>
                  }
                } @else {
                  <div class="slot-empty">Loading…</div>
                }
              </div>
            }
          </div>
        }
      }
    </section>
  `,
  styles: [
    `
      .surface-header {
        margin-bottom: 16px;
      }

      .surface-kicker {
        margin: 0 0 6px;
        text-transform: uppercase;
        letter-spacing: 0.1em;
        font-size: 0.74rem;
        color: #516661;
      }

      h3 {
        margin: 0;
      }

      .loading-grid {
        display: grid;
        gap: 14px;
      }

      .loading-card {
        min-height: 180px;
        border-radius: 22px;
        background: linear-gradient(
          90deg,
          rgba(231, 221, 209, 0.95),
          rgba(247, 241, 232, 0.95),
          rgba(231, 221, 209, 0.95)
        );
        background-size: 200% 100%;
        animation: shimmer 1.25s linear infinite;
      }

      .tier-tabs {
        display: flex;
        gap: 8px;
        margin-bottom: 16px;
        overflow-x: auto;
      }

      .tier-tab {
        appearance: none;
        border: 1px solid rgba(17, 35, 31, 0.12);
        border-radius: 999px;
        padding: 8px 16px;
        background: rgba(255, 255, 255, 0.8);
        color: #204f46;
        cursor: pointer;
        font: inherit;
        font-size: 0.9rem;
        white-space: nowrap;
        transition:
          background 150ms ease,
          border-color 150ms ease;
      }

      .tier-tab:hover {
        background: rgba(215, 239, 231, 0.6);
      }

      .tier-tab.active {
        background: #204f46;
        color: white;
        border-color: #204f46;
      }

      .tier-description {
        margin: 0 0 16px;
        color: #516661;
        line-height: 1.5;
        font-size: 0.95rem;
      }

      .slot-carousel {
        display: flex;
        gap: 14px;
        overflow-x: auto;
        scroll-snap-type: x mandatory;
        padding-bottom: 8px;
      }

      .slot-card {
        flex: 0 0 200px;
        scroll-snap-align: start;
        padding: 14px;
        border-radius: 18px;
        background: rgba(246, 242, 232, 0.9);
        border: 1px solid rgba(17, 35, 31, 0.08);
        display: flex;
        flex-direction: column;
        gap: 8px;
      }

      .slot-label {
        text-transform: uppercase;
        letter-spacing: 0.08em;
        font-size: 0.7rem;
        color: #516661;
      }

      .slot-image {
        width: 100%;
        height: 120px;
        object-fit: cover;
        border-radius: 12px;
        background: #f0ece4;
      }

      .slot-name {
        font-size: 0.9rem;
      }

      .slot-brand {
        color: #516661;
        font-size: 0.82rem;
      }

      .slot-price {
        font-weight: 600;
        color: #204f46;
        font-size: 0.9rem;
      }

      .slot-empty {
        height: 120px;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 12px;
        background: rgba(231, 221, 209, 0.6);
        color: #516661;
        font-size: 0.85rem;
      }

      @keyframes shimmer {
        0% {
          background-position: 200% 0;
        }
        100% {
          background-position: -200% 0;
        }
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BundleDisplayComponent {
  protected readonly placeholders = Array.from({length: 1});
  readonly surface = input.required<BundleDisplaySurface>();

  protected readonly activeTierId = signal('');

  protected readonly activeTier = computed(() => {
    const bundles = this.surface().bundles;
    if (bundles.length === 0) return null;

    const id = this.activeTierId();
    const found = bundles.find((b) => b.bundleId === id);
    return found ?? bundles[0];
  });

  protected isActive(bundleId: string): boolean {
    const tier = this.activeTier();
    return tier?.bundleId === bundleId;
  }

  protected selectTier(bundleId: string): void {
    this.activeTierId.set(bundleId);
  }

  protected formatPrice(value: number): string {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
    }).format(value);
  }
}

// samples/commerce-agent-chat/vue/src/components/commerce/BundleDisplay.vue
<script setup lang="ts">
import {ref} from 'vue';
import type {BundleTierConfig, Product} from '@core/types/commerce.js';
import PriceDisplay from './PriceDisplay.vue';

interface BundleSlotWithProduct {
  categoryLabel: string;
  surfaceRef: string;
  product: Product | null;
}

export interface BundleTierWithProducts extends Omit<
  BundleTierConfig,
  'slots'
> {
  slots: BundleSlotWithProduct[];
}

const props = defineProps<{
  title: string;
  bundles: BundleTierWithProducts[];
  isLoading?: boolean;
}>();

const activeIndex = ref(0);
</script>

<template>
  <div
    v-if="props.bundles.length === 0 && (props.isLoading ?? false)"
    class="bundle-display"
    aria-busy="true"
  >
    <h3 class="commerce-heading">{{ title }}</h3>
    <div class="bundle-slots">
      <div
        v-for="i in 3"
        :key="`bundle-skeleton-${i}`"
        class="bundle-slot"
        aria-hidden="true"
      >
        <div class="commerce-loading commerce-loading--line" />
        <div class="commerce-loading commerce-loading--image" />
        <div
          class="commerce-loading commerce-loading--line commerce-loading--line-wide"
        />
      </div>
    </div>
  </div>

  <div v-else-if="props.bundles.length > 0" class="bundle-display">
    <h3 class="commerce-heading">{{ title }}</h3>
    <div
      v-if="props.bundles.length > 1"
      class="bundle-tabs"
      role="tablist"
      aria-label="Bundle tiers"
    >
      <button
        v-for="(bundle, i) in props.bundles"
        :key="bundle.bundleId"
        type="button"
        role="tab"
        :aria-selected="i === activeIndex"
        :class="['bundle-tab', {' bundle-tab--active': i === activeIndex}]"
        @click="activeIndex = i"
      >
        {{ bundle.label }}
      </button>
    </div>

    <div
      v-for="(bundle, i) in props.bundles"
      v-show="i === activeIndex"
      :key="`${bundle.bundleId}-${i}`"
      role="tabpanel"
    >
      <p v-if="bundle.description" class="bundle-description">
        {{ bundle.description }}
      </p>
      <div class="bundle-slots">
        <div
          v-for="(slot, j) in bundle.slots"
          :key="`${slot.surfaceRef}-${j}`"
          class="bundle-slot"
        >
          <p class="bundle-slot__label">{{ slot.categoryLabel }}</p>
          <template v-if="slot.product">
            <img
              v-if="slot.product.ec_image"
              :src="slot.product.ec_image"
              :alt="slot.product.ec_name"
              class="bundle-slot__image"
            />
            <p class="bundle-slot__name">{{ slot.product.ec_name }}</p>
            <p class="bundle-slot__brand">{{ slot.product.ec_brand }}</p>
            <PriceDisplay :product="slot.product" />
          </template>
          <p v-else class="text-muted">Product not available</p>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.bundle-display {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.bundle-tabs {
  display: flex;
  gap: 0.4rem;
  flex-wrap: wrap;
}

.bundle-tab {
  padding: 0.4rem 0.9rem;
  border: 2px solid rgba(0, 212, 255, 0.3);
  border-radius: 10px;
  background: rgba(22, 45, 66, 0.5);
  color: var(--ink);
  font: inherit;
  font-size: 0.84rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
}

.bundle-tab--active {
  background: linear-gradient(
    135deg,
    var(--accent-warm) 0%,
    var(--accent) 100%
  );
  color: #000;
  border-color: var(--accent);
  box-shadow: 0 0 20px rgba(0, 212, 255, 0.4);
}

.bundle-tab:hover {
  border-color: var(--accent);
  box-shadow: 0 0 15px rgba(0, 212, 255, 0.2);
}

.bundle-description {
  margin: 0 0 0.5rem;
  font-size: 0.82rem;
  color: var(--ink-muted);
}

.bundle-slots {
  display: flex;
  gap: 0.65rem;
  overflow-x: auto;
  padding-bottom: 0.25rem;
}

.bundle-slot {
  flex: 0 0 160px;
  border: 2px solid rgba(0, 212, 255, 0.3);
  border-radius: 12px;
  background: linear-gradient(
    135deg,
    rgba(22, 45, 66, 0.5) 0%,
    rgba(26, 58, 82, 0.3) 100%
  );
  padding: 0.7rem;
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  transition: all 0.3s ease;
  box-shadow: 0 0 12px rgba(0, 212, 255, 0.1);
  backdrop-filter: blur(5px);
}

.bundle-slot:hover {
  border-color: rgba(0, 212, 255, 0.6);
  box-shadow: 0 0 25px rgba(0, 212, 255, 0.2);
  transform: translateY(-2px);
}

.bundle-slot__label {
  margin: 0;
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--accent);
}

.bundle-slot__image {
  width: 100%;
  height: 90px;
  object-fit: cover;
  border-radius: 8px;
  border: 1px solid rgba(0, 212, 255, 0.2);
  display: block;
}

.bundle-slot__name {
  margin: 0;
  font-size: 0.8rem;
  font-weight: 600;
  color: var(--ink);
}

.bundle-slot__brand {
  margin: 0;
  font-size: 0.72rem;
  color: var(--ink-muted);
}

.text-muted {
  color: var(--ink-muted);
  font-size: 0.8rem;
}
</style>
