// samples/commerce-agent-chat/react/src/components/commerce/ComparisonSummary.tsx
import {useEffect, useRef} from 'react';

interface ComparisonSummaryElement extends HTMLElement {
  text: string;
}

interface ComparisonSummaryProps {
  text: string;
}

export function ComparisonSummary({text}: ComparisonSummaryProps) {
  const elementRef = useRef<ComparisonSummaryElement | null>(null);

  useEffect(() => {
    if (elementRef.current) {
      elementRef.current.text = text;
    }
  }, [text]);

  return <cac-comparison-summary ref={elementRef} />;
}

// samples/commerce-agent-chat/vue/src/components/commerce/ComparisonSummary.vue
<script setup lang="ts">
import {ref, watchEffect} from 'vue';

interface ComparisonSummaryElement extends HTMLElement {
  text: string;
}

const props = defineProps<{text: string}>();
const elementRef = ref<ComparisonSummaryElement | null>(null);

watchEffect(() => {
  if (elementRef.value) {
    elementRef.value.text = props.text;
  }
});
</script>

<template>
  <cac-comparison-summary ref="elementRef" />
</template>
