// samples/commerce-agent-chat/react/src/components/commerce/NextActionsBar.tsx
import {useEffect, useRef} from 'react';
import type {NextAction} from '@core/types/commerce.js';

interface NextActionsBarProps {
  actions: NextAction[];
  isLoading?: boolean;
  onActionClick?: (prompt: string) => void;
}

interface NextActionsBarElement extends HTMLElement {
  actions: NextAction[];
  isLoading: boolean;
}

interface CommerceActionClickEventDetail {
  prompt: string;
}

export function NextActionsBar({
  actions,
  isLoading = false,
  onActionClick,
}: NextActionsBarProps) {
  const elementRef = useRef<NextActionsBarElement | null>(null);

  useEffect(() => {
    if (elementRef.current) {
      elementRef.current.actions = actions;
      elementRef.current.isLoading = isLoading;
    }
  }, [actions, isLoading]);

  useEffect(() => {
    if (!elementRef.current) {
      return;
    }

    const handler = (event: Event) => {
      const customEvent = event as CustomEvent<CommerceActionClickEventDetail>;
      onActionClick?.(customEvent.detail.prompt);
    };

    elementRef.current.addEventListener('commerce-action-click', handler);
    return () => {
      elementRef.current?.removeEventListener('commerce-action-click', handler);
    };
  }, [onActionClick]);

  return <cac-next-actions-bar ref={elementRef} />;
}

// samples/commerce-agent-chat/vue/src/components/commerce/NextActionsBar.vue
<script setup lang="ts">
import {onBeforeUnmount, onMounted, ref, watchEffect} from 'vue';
import type {NextAction} from '@core/types/commerce.js';

const props = defineProps<{
  actions: NextAction[];
  isLoading?: boolean;
}>();

const emit = defineEmits<{
  actionClick: [prompt: string];
}>();

interface NextActionsBarElement extends HTMLElement {
  actions: NextAction[];
  isLoading: boolean;
}

interface CommerceActionClickEventDetail {
  prompt: string;
}

const elementRef = ref<NextActionsBarElement | null>(null);

const onActionClick = (event: Event) => {
  const customEvent = event as CustomEvent<CommerceActionClickEventDetail>;
  emit('actionClick', customEvent.detail.prompt);
};

watchEffect(() => {
  if (elementRef.value) {
    elementRef.value.actions = props.actions;
    elementRef.value.isLoading = props.isLoading ?? false;
  }
});

onMounted(() => {
  elementRef.value?.addEventListener('commerce-action-click', onActionClick);
});

onBeforeUnmount(() => {
  elementRef.value?.removeEventListener('commerce-action-click', onActionClick);
});
</script>

<template>
  <cac-next-actions-bar ref="elementRef" />
</template>
