// samples/thermidor/generative-angular/src/app/components/product-carousel.component.ts
import {ChangeDetectionStrategy, Component, input} from '@angular/core';
import {ProductCarouselSurface} from '../models';

@Component({
  selector: 'app-product-carousel',
  template: `
    <section class="surface">
      <header class="surface-header">
        <p class="surface-kicker">Product Carousel</p>
        <h3>{{ surface().heading }}</h3>
      </header>

      @if (surface().isLoading || surface().products.length === 0) {
        <div class="loading-grid">
          @for (item of placeholders; track $index) {
            <div class="loading-card"></div>
          }
        </div>
      } @else {
        <div class="carousel">
          @for (item of surface().products; track item.ec_product_id) {
            <article class="card">
              @if (item.ec_image) {
                <img
                  class="product-image"
                  [src]="item.ec_image"
                  [alt]="item.ec_name"
                  loading="lazy"
                />
              } @else {
                <div
                  class="swatch"
                  [style.background]="
                    item.accent || 'linear-gradient(135deg, #e7d8c8, #c6a889)'
                  "
                ></div>
              }
              <p class="brand">{{ item.ec_brand }}</p>
              <h4>{{ item.ec_name }}</h4>
              <p class="description">
                {{ item.description || 'Barca Sports product' }}
              </p>
              <div class="footer">
                <strong>{{
                  formatPrice(item.ec_promo_price ?? item.ec_price)
                }}</strong>
                <span>{{
                  item.ec_promo_price ? 'Sale price' : 'View details'
                }}</span>
              </div>
            </article>
          }
        </div>
      }
    </section>
  `,
  styles: [
    `
      .surface-header {
        margin-bottom: 16px;
      }

      .surface-kicker,
      .brand,
      .meta {
        margin: 0 0 6px;
        text-transform: uppercase;
        letter-spacing: 0.1em;
        font-size: 0.74rem;
        color: #516661;
      }

      h3,
      h4 {
        margin: 0;
      }

      .carousel,
      .loading-grid {
        display: flex;
        gap: 14px;
        overflow-x: auto;
        scroll-snap-type: x mandatory;
        padding-bottom: 8px;
      }

      .card,
      .loading-card {
        flex: 0 0 240px;
        scroll-snap-align: start;
        border-radius: 22px;
        padding: 16px;
        border: 1px solid rgba(17, 35, 31, 0.12);
        background: rgba(255, 255, 255, 0.8);
      }

      .loading-card {
        min-height: 220px;
        background: linear-gradient(
          90deg,
          rgba(231, 221, 209, 0.95),
          rgba(247, 241, 232, 0.95),
          rgba(231, 221, 209, 0.95)
        );
        background-size: 200% 100%;
        animation: shimmer 1.25s linear infinite;
      }

      .product-image {
        width: 100%;
        height: 140px;
        object-fit: cover;
        border-radius: 16px;
        margin-bottom: 12px;
        background: #f0ece4;
      }

      .swatch {
        width: 100%;
        height: 140px;
        border-radius: 16px;
        margin-bottom: 12px;
      }

      .description {
        margin: 12px 0;
        color: #516661;
        line-height: 1.5;
      }

      .meta {
        display: flex;
        gap: 10px;
        flex-wrap: wrap;
      }

      .footer {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 12px;
        margin-top: 12px;
      }

      .footer span {
        color: #204f46;
      }

      @keyframes shimmer {
        0% {
          background-position: 200% 0;
        }
        100% {
          background-position: -200% 0;
        }
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductCarouselComponent {
  protected readonly placeholders = Array.from({length: 3});
  readonly surface = input.required<ProductCarouselSurface>();

  protected formatPrice(value: number): string {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0,
    }).format(value);
  }
}

// samples/commerce-agent-chat/vue/src/components/commerce/ProductCarousel.vue
<script setup lang="ts">
import type {Product} from '@core/types/commerce.js';
import PriceDisplay from './PriceDisplay.vue';

export interface ProductSection {
  heading: string;
  products: Product[];
}

defineProps<{
  sections: ProductSection[];
  isLoading?: boolean;
}>();
</script>

<template>
  <div v-if="sections.length > 0" class="product-carousel">
    <div
      v-for="(section, i) in sections"
      :key="`${section.heading}-${i}`"
      class="carousel-section"
    >
      <template v-if="(isLoading ?? false) && section.products.length === 0">
        <h3 class="commerce-heading">{{ section.heading }}</h3>
        <div
          class="carousel-track"
          role="list"
          aria-label="Loading products"
          aria-busy="true"
        >
          <div
            v-for="j in 3"
            :key="`carousel-skeleton-${j}`"
            role="listitem"
            class="carousel-track__item"
          >
            <article class="product-card product-card--skeleton">
              <div
                class="product-card__image commerce-loading commerce-loading--image"
              />
              <div class="product-card__body">
                <div class="commerce-loading commerce-loading--line" />
                <div
                  class="commerce-loading commerce-loading--line commerce-loading--line-wide"
                />
              </div>
            </article>
          </div>
        </div>
      </template>
      <template v-else>
        <h3 class="commerce-heading">{{ section.heading }}</h3>
        <div class="carousel-track" role="list">
          <div
            v-for="product in section.products"
            :key="product.ec_product_id"
            role="listitem"
            class="carousel-track__item"
          >
            <article class="product-card">
              <img
                v-if="product.ec_image"
                :src="product.ec_image"
                :alt="product.ec_name"
                class="product-card__image"
              />
              <div
                v-else
                class="product-card__image product-card__image--placeholder"
                aria-hidden="true"
              />
              <div class="product-card__body">
                <p class="product-card__name">{{ product.ec_name }}</p>
                <p class="product-card__brand">{{ product.ec_brand }}</p>
                <PriceDisplay :product="product" />
              </div>
            </article>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<style scoped>
.product-carousel {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.carousel-section {
  display: flex;
  flex-direction: column;
  gap: 0.4rem;
}

.carousel-track {
  display: flex;
  gap: 0.75rem;
  overflow-x: auto;
  padding-top: 0.4rem;
  padding-bottom: 0.4rem;
  scroll-snap-type: x mandatory;
}

.carousel-track::-webkit-scrollbar {
  height: 4px;
}

.carousel-track::-webkit-scrollbar-track {
  background: var(--bg-1);
}

.carousel-track::-webkit-scrollbar-thumb {
  background: var(--border);
  border-radius: 2px;
}

.carousel-track__item {
  flex: 0 0 180px;
  min-width: 180px;
}

.product-card {
  flex: 0 0 180px;
  border: 2px solid rgba(0, 212, 255, 0.3);
  border-radius: 12px;
  background: linear-gradient(
    135deg,
    rgba(22, 45, 66, 0.6) 0%,
    rgba(26, 58, 82, 0.4) 100%
  );
  overflow: hidden;
  scroll-snap-align: start;
  transition: all 0.3s ease;
  box-shadow: 0 0 15px rgba(0, 212, 255, 0.1);
  backdrop-filter: blur(5px);
}

.product-card:hover {
  border-color: rgba(0, 212, 255, 0.6);
  box-shadow: 0 0 30px rgba(0, 212, 255, 0.25);
  transform: translateY(-4px);
}

.product-card__image {
  width: 100%;
  height: 110px;
  object-fit: cover;
  display: block;
  border-bottom: 1px solid rgba(0, 212, 255, 0.2);
}

.product-card__image--placeholder {
  background: linear-gradient(
    45deg,
    rgba(0, 212, 255, 0.1),
    rgba(0, 212, 255, 0.05)
  );
}

.product-card--skeleton .product-card__body {
  gap: 0.45rem;
}

.product-card__body {
  padding: 0.5rem 0.65rem;
  display: flex;
  flex-direction: column;
  gap: 0.2rem;
}

.product-card__name {
  margin: 0;
  font-size: 0.8rem;
  font-weight: 600;
  color: var(--ink);
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.product-card__brand {
  margin: 0;
  font-size: 0.72rem;
  color: var(--ink-muted);
}
</style>
