// samples/commerce-agent-chat/vue/src/components/commerce/CommerceCatalogView.vue
<script setup lang="ts">
import {computed} from 'vue';

import {
  extractActionsBySurface,
  extractCatalogComponents,
  extractProductsBySurface,
} from '@core/lib/commerceExtractor.js';
import {
  isType,
  isSupportedType,
  uniqueProducts,
} from '@core/lib/commerceHelpers.js';
import {
  getBundleProductsFromCache,
  updateBundleProductCache,
} from '@core/lib/bundleProductCache.js';
import type {A2UISurfaceContent, Product} from '@core/types/commerce.js';
import BundleDisplay, {type BundleTierWithProducts} from './BundleDisplay.vue';
import ComparisonSummary from './ComparisonSummary.vue';
import ComparisonTable from './ComparisonTable.vue';
import NextActionsBar from './NextActionsBar.vue';
import ProductCarousel, {type ProductSection} from './ProductCarousel.vue';

const props = defineProps<{
  content: A2UISurfaceContent;
  isLoading?: boolean;
}>();

const emit = defineEmits<{
  actionSelected: [prompt: string];
}>();

const model = computed(() => {
  const operations = props.content?.operations ?? [];
  const productsBySurface = extractProductsBySurface(operations);
  updateBundleProductCache(productsBySurface);

  const actionsBySurface = extractActionsBySurface(operations);
  const components = extractCatalogComponents(operations).filter((component) =>
    isSupportedType(component.type)
  );
  const allProducts = uniqueProducts(productsBySurface);

  const comparisonBySurface = new Map<string, Product[]>();
  for (const component of components) {
    if (!isType(component.type, 'ComparisonTable')) {
      continue;
    }
    const products =
      productsBySurface.get(component.surfaceId) ??
      getBundleProductsFromCache(component.surfaceId);
    comparisonBySurface.set(
      component.surfaceId,
      products.length > 0 ? products : allProducts
    );
  }

  const hasNextActionsComponent = components.some((component) =>
    isType(component.type, 'NextActionsBar')
  );

  return {
    productsBySurface,
    actionsBySurface,
    components,
    comparisonBySurface,
    hasNextActionsComponent,
  };
});

function getProducts(surfaceId: string): Product[] {
  return (
    model.value.productsBySurface.get(surfaceId) ??
    getBundleProductsFromCache(surfaceId)
  );
}

function buildBundles(
  component: (typeof model.value.components)[number]
): BundleTierWithProducts[] {
  return (component.bundles ?? []).map((bundle) => ({
    ...bundle,
    slots: bundle.slots.map((slot) => ({
      ...slot,
      surfaceRef: slot.surfaceRef.trim(),
      product: getProducts(slot.surfaceRef.trim())[0] ?? null,
    })),
  }));
}
</script>

<template>
  <section class="commerce-catalog">
    <template
      v-for="(component, index) in model.components"
      :key="`${component.type}-${component.surfaceId}-${index}`"
    >
      <ProductCarousel
        v-if="isType(component.type, 'ProductCarousel')"
        :sections="
          [
            {
              heading: component.heading,
              products: getProducts(component.surfaceId),
            },
          ] as ProductSection[]
        "
        :is-loading="
          (props.isLoading ?? false) &&
          getProducts(component.surfaceId).length === 0
        "
      />

      <ComparisonSummary
        v-else-if="isType(component.type, 'ComparisonSummary')"
        :text="component.text ?? ''"
      />

      <ComparisonTable
        v-else-if="isType(component.type, 'ComparisonTable')"
        :heading="component.heading"
        :products="model.comparisonBySurface.get(component.surfaceId) ?? []"
        :attributes="component.attributes ?? []"
        :is-loading="
          (props.isLoading ?? false) &&
          (model.comparisonBySurface.get(component.surfaceId)?.length ?? 0) ===
            0
        "
      />

      <BundleDisplay
        v-else-if="isType(component.type, 'BundleDisplay')"
        :title="component.title ?? component.heading"
        :bundles="buildBundles(component)"
        :is-loading="props.isLoading ?? false"
      />

      <NextActionsBar
        v-else-if="isType(component.type, 'NextActionsBar')"
        :actions="model.actionsBySurface.get(component.surfaceId) ?? []"
        :is-loading="
          (props.isLoading ?? false) &&
          (model.actionsBySurface.get(component.surfaceId)?.length ?? 0) === 0
        "
        @action-click="emit('actionSelected', $event)"
      />
    </template>

    <NextActionsBar
      v-if="(props.isLoading ?? false) && !model.hasNextActionsComponent"
      :actions="[]"
      :is-loading="true"
      @action-click="emit('actionSelected', $event)"
    />
  </section>
</template>

<style scoped>
.commerce-catalog {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}
</style>

// samples/commerce-agent-chat/react/src/components/commerce/CommerceCatalogView.tsx
import type {Product} from '@core/types/commerce.js';
import type {A2UISurfaceContent} from '@core/types/commerce.js';
import {
  extractActionsBySurface,
  extractCatalogComponents,
  extractProductsBySurface,
} from '@core/lib/commerceExtractor.js';
import {
  isSupportedType,
  isType,
  uniqueProducts,
} from '@core/lib/commerceHelpers.js';
import {
  getBundleProductsFromCache,
  resetBundleProductCache,
  updateBundleProductCache,
} from '@core/lib/bundleProductCache.js';
import {BundleDisplay} from './BundleDisplay.js';
import {ComparisonSummary} from './ComparisonSummary.js';
import {ComparisonTable} from './ComparisonTable.js';
import {NextActionsBar} from './NextActionsBar.js';
import {ProductCarousel, type ProductSection} from './ProductCarousel.js';

export function resetCommerceCatalogCache(): void {
  resetBundleProductCache();
}

function hasBundleSlotProduct(
  bundles: Array<{slots: Array<{product: Product | null}>}>
): boolean {
  return bundles.some((bundle) =>
    bundle.slots.some((slot) => slot.product !== null)
  );
}

export function CommerceCatalogView({
  content,
  isLoading = false,
  onActionSelected,
}: {
  content: A2UISurfaceContent;
  isLoading?: boolean;
  onActionSelected?: (prompt: string) => void;
}) {
  const {operations} = content;
  const productsBySurface = extractProductsBySurface(operations);

  updateBundleProductCache(productsBySurface);

  const getProducts = (surfaceId: string): Product[] =>
    productsBySurface.get(surfaceId) ?? getBundleProductsFromCache(surfaceId);

  const catalogComponents = extractCatalogComponents(operations);
  const actionsBySurface = extractActionsBySurface(operations);
  const supported = catalogComponents.filter((c) => isSupportedType(c.type));
  const hasNextActionsComponent = supported.some((component) =>
    isType(component.type, 'NextActionsBar')
  );

  const allProducts = uniqueProducts(productsBySurface);

  if (supported.length === 0) return null;

  return (
    <div className="commerce-catalog">
      {supported.map((comp, i) => {
        if (isType(comp.type, 'ProductCarousel')) {
          const products = getProducts(comp.surfaceId);
          const sections: ProductSection[] = [
            {heading: comp.heading, products},
          ];
          const inferredLoading = isLoading && products.length === 0;
          return (
            <ProductCarousel
              key={`product-carousel-${i}`}
              sections={sections}
              isLoading={(comp.isLoading ?? false) || inferredLoading}
            />
          );
        }

        if (isType(comp.type, 'ComparisonTable')) {
          const products = getProducts(comp.surfaceId);
          const comparisonProducts =
            products.length > 0 ? products : allProducts;
          const inferredLoading = isLoading && comparisonProducts.length === 0;
          return (
            <ComparisonTable
              key={`comparison-table-${i}`}
              heading={comp.heading}
              products={comparisonProducts}
              attributes={comp.attributes ?? []}
              isLoading={(comp.isLoading ?? false) || inferredLoading}
            />
          );
        }

        if (isType(comp.type, 'ComparisonSummary')) {
          return (
            <ComparisonSummary
              key={`comparison-summary-${i}`}
              text={comp.text ?? ''}
            />
          );
        }

        if (isType(comp.type, 'BundleDisplay')) {
          const bundles = (comp.bundles ?? []).map((bundle) => ({
            ...bundle,
            slots: bundle.slots.map((slot) => ({
              ...slot,
              surfaceRef: slot.surfaceRef.trim(),
              product: getProducts(slot.surfaceRef.trim())[0] ?? null,
            })),
          }));
          const inferredLoading = isLoading && !hasBundleSlotProduct(bundles);
          return (
            <BundleDisplay
              key={`bundle-display-${i}`}
              title={comp.title ?? comp.heading}
              bundles={bundles}
              isLoading={(comp.isLoading ?? false) || inferredLoading}
            />
          );
        }

        if (isType(comp.type, 'NextActionsBar')) {
          const actions = actionsBySurface.get(comp.surfaceId) ?? [];
          const inferredLoading = isLoading && actions.length === 0;
          return (
            <NextActionsBar
              key={`next-actions-${i}`}
              actions={actions}
              isLoading={(comp.isLoading ?? false) || inferredLoading}
              onActionClick={onActionSelected}
            />
          );
        }

        return null;
      })}
      {isLoading && !hasNextActionsComponent ? (
        <NextActionsBar actions={[]} isLoading={true} />
      ) : null}
    </div>
  );
}
