// samples/commerce-agent-chat/vue/src/components/commerce/ComparisonTable.vue
<script setup lang="ts">
import {ref, watchEffect} from 'vue';
import type {Product} from '@core/types/commerce.js';

const props = defineProps<{
  heading: string;
  products: Product[];
  attributes?: string[];
  isLoading?: boolean;
}>();

interface ComparisonTableElement extends HTMLElement {
  heading: string;
  products: Product[];
  comparisonAttributes: string[];
  isLoading: boolean;
}

const elementRef = ref<ComparisonTableElement | null>(null);

watchEffect(() => {
  if (elementRef.value) {
    elementRef.value.heading = props.heading;
    elementRef.value.products = props.products;
    elementRef.value.comparisonAttributes = props.attributes ?? [];
    elementRef.value.isLoading = props.isLoading ?? false;
  }
});
</script>

<template>
  <cac-comparison-table ref="elementRef" />
</template>

// samples/commerce-agent-chat/react/src/components/commerce/ComparisonTable.tsx
import type {Product} from '@core/types/commerce.js';
import {useEffect, useRef} from 'react';

interface ComparisonTableProps {
  heading: string;
  products: Product[];
  attributes?: string[];
  isLoading?: boolean;
}

interface ComparisonTableElement extends HTMLElement {
  heading: string;
  products: Product[];
  comparisonAttributes: string[];
  isLoading: boolean;
}

export function ComparisonTable({
  heading,
  products,
  attributes = [],
  isLoading = false,
}: ComparisonTableProps) {
  const elementRef = useRef<ComparisonTableElement | null>(null);

  useEffect(() => {
    if (elementRef.current) {
      elementRef.current.heading = heading;
      elementRef.current.products = products;
      elementRef.current.comparisonAttributes = attributes;
      elementRef.current.isLoading = isLoading;
    }
  }, [heading, products, attributes, isLoading]);

  return <cac-comparison-table ref={elementRef} />;
}
