// samples/commerce-agent-chat/vue/src/components/commerce/PriceDisplay.vue
<script setup lang="ts">
import {ref, watchEffect} from 'vue';
import type {Product} from '@core/types/commerce.js';

const props = defineProps<{product: Product}>();

interface PriceDisplayElement extends HTMLElement {
  product: Product;
}

const elementRef = ref<PriceDisplayElement | null>(null);

watchEffect(() => {
  if (elementRef.value) {
    elementRef.value.product = props.product;
  }
});
</script>

<template>
  <cac-price-display ref="elementRef" />
</template>

// samples/commerce-agent-chat/react/src/components/commerce/PriceDisplay.tsx
import {useEffect, useRef} from 'react';
import type {Product} from '@core/types/commerce.js';

interface PriceDisplayElement extends HTMLElement {
  product: Product;
}

export function PriceDisplay({product}: {product: Product}) {
  const elementRef = useRef<PriceDisplayElement | null>(null);

  useEffect(() => {
    if (elementRef.current) {
      elementRef.current.product = product;
    }
  }, [product]);

  return <cac-price-display ref={elementRef} />;
}
