// samples/commerce-agent-chat/vue/src/components/commerce/ProductCarousel.vue
<script setup lang="ts">
import {ref, watchEffect} from 'vue';
import type {Product} from '@core/types/commerce.js';

export interface ProductSection {
  heading: string;
  products: Product[];
}

const props = defineProps<{
  sections: ProductSection[];
  isLoading?: boolean;
}>();

interface ProductCarouselElement extends HTMLElement {
  sections: ProductSection[];
  isLoading: boolean;
}

const elementRef = ref<ProductCarouselElement | null>(null);

watchEffect(() => {
  if (elementRef.value) {
    elementRef.value.sections = props.sections;
    elementRef.value.isLoading = props.isLoading ?? false;
  }
});
</script>

<template>
  <cac-product-carousel ref="elementRef" />
</template>

// samples/commerce-agent-chat/react/src/components/commerce/ProductCarousel.tsx
import type {Product} from '@core/types/commerce.js';
import {useEffect, useRef} from 'react';

export interface ProductSection {
  heading: string;
  products: Product[];
}

interface ProductCarouselProps {
  sections: ProductSection[];
  isLoading?: boolean;
}

interface ProductCarouselElement extends HTMLElement {
  sections: ProductSection[];
  isLoading: boolean;
}

export function ProductCarousel({
  sections,
  isLoading = false,
}: ProductCarouselProps) {
  const elementRef = useRef<ProductCarouselElement | null>(null);

  useEffect(() => {
    if (elementRef.current) {
      elementRef.current.sections = sections;
      elementRef.current.isLoading = isLoading;
    }
  }, [sections, isLoading]);

  return <cac-product-carousel ref={elementRef} />;
}
