// samples/commerce-agent-chat/vue/src/App.vue
<script setup lang="ts">
import {ref} from 'vue';

import {loadConfig, type CommerceConfig} from '@core/config/env.js';

import ChatInterface from './components/ChatInterface.vue';

const config = ref<CommerceConfig | null>(null);
const error = ref<string | null>(null);

try {
  config.value = loadConfig();
} catch (err) {
  error.value = err instanceof Error ? err.message : 'Configuration failed';
}
</script>

<template>
  <main v-if="error" class="state-screen" role="alert">
    <section class="state-card">
      <h1>Configuration Error</h1>
      <pre>{{ error }}</pre>
    </section>
  </main>

  <main v-else-if="!config" class="state-screen" aria-live="polite">
    <section class="state-card">Loading configuration...</section>
  </main>

  <ChatInterface v-else :config="config" />
</template>

// samples/commerce-agent-chat/react/src/App.tsx
import {useEffect, useState} from 'react';

import {ChatInterface} from './components/ChatInterface.js';
import {loadConfig, type CommerceConfig} from '@core/config/env.js';
import './App.css';

export function App(): React.JSX.Element {
  const [config, setConfig] = useState<CommerceConfig | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    try {
      setConfig(loadConfig());
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Configuration failed');
    }
  }, []);

  if (error) {
    return (
      <main className="state-screen" role="alert">
        <section className="state-card">
          <h1>Configuration Error</h1>
          <pre>{error}</pre>
        </section>
      </main>
    );
  }

  if (!config) {
    return (
      <main className="state-screen" aria-live="polite">
        <section className="state-card">Loading configuration...</section>
      </main>
    );
  }

  return <ChatInterface config={config} />;
}
