// samples/commerce-agent-chat/react/src/components/ActivityRenderer.tsx
import type {ActivityMessage} from '@core/types/agent.js';
import {useEffect, useRef} from 'react';

interface CommerceActionClickEvent extends CustomEvent<{prompt: string}> {}

interface ActivityRendererProps {
  activity: ActivityMessage;
  isLoading?: boolean;
  onActionSelected?: (prompt: string) => void;
}

interface ActivityRendererElement extends HTMLElement {
  activity: ActivityMessage;
  isLoading: boolean;
}

export function ActivityRenderer({
  activity,
  isLoading = false,
  onActionSelected,
}: ActivityRendererProps): React.JSX.Element {
  const elementRef = useRef<ActivityRendererElement | null>(null);

  useEffect(() => {
    if (elementRef.current) {
      elementRef.current.activity = activity;
      elementRef.current.isLoading = isLoading;
    }
  }, [activity, isLoading]);

  useEffect(() => {
    const element = elementRef.current;
    if (!element || !onActionSelected) {
      return;
    }

    const handleActionClick = (event: Event) => {
      onActionSelected((event as CommerceActionClickEvent).detail.prompt);
    };

    element.addEventListener('commerce-action-click', handleActionClick);
    return () =>
      element.removeEventListener('commerce-action-click', handleActionClick);
  }, [onActionSelected]);

  return <cac-activity-renderer ref={elementRef} />;
}

// samples/commerce-agent-chat/vue/src/components/ActivityRenderer.vue
<script setup lang="ts">
import {onMounted, onUnmounted, ref, watchEffect} from 'vue';
import type {ActivityMessage} from '@core/types/agent.js';

const props = defineProps<{
  activity: ActivityMessage;
  isLoading?: boolean;
}>();

const emit = defineEmits<{
  actionSelected: [prompt: string];
}>();

interface CommerceActionClickEvent extends CustomEvent<{prompt: string}> {}

interface ActivityRendererElement extends HTMLElement {
  activity: ActivityMessage;
  isLoading: boolean;
}

const elementRef = ref<ActivityRendererElement | null>(null);

watchEffect(() => {
  if (elementRef.value) {
    elementRef.value.activity = props.activity;
    elementRef.value.isLoading = props.isLoading ?? false;
  }
});

function handleActionClick(event: Event) {
  emit('actionSelected', (event as CommerceActionClickEvent).detail.prompt);
}

onMounted(() => {
  elementRef.value?.addEventListener(
    'commerce-action-click',
    handleActionClick
  );
});

onUnmounted(() => {
  elementRef.value?.removeEventListener(
    'commerce-action-click',
    handleActionClick
  );
});
</script>

<template>
  <cac-activity-renderer ref="elementRef" />
</template>
