// samples/commerce-agent-chat/angular/src/app/components/activity-renderer.component.ts
import {CommonModule, JsonPipe} from '@angular/common';
import {Component, EventEmitter, Input, Output} from '@angular/core';

import type {ActivityMessage} from '@core/types/agent.js';
import type {A2UISurfaceContent} from '@core/types/commerce.js';

import {CommerceCatalogViewComponent} from './commerce-catalog-view.component';

@Component({
  selector: 'app-activity-renderer',
  standalone: true,
  imports: [CommonModule, JsonPipe, CommerceCatalogViewComponent],
  template: `
    <article class="activity-renderer" aria-label="Agent activity">
      @if (activity.activityType === 'a2ui-surface') {
        <app-commerce-catalog-view
          [content]="surfaceContent"
          [isLoading]="isLoading"
          (actionSelected)="actionSelected.emit($event)"
        />
      } @else {
        <p class="activity-type">{{ activity.activityType }}</p>
        <pre class="activity-content">{{ activity.content | json }}</pre>
      }
    </article>
  `,
})
export class ActivityRendererComponent {
  @Input({required: true}) activity!: ActivityMessage;
  @Input() isLoading = false;
  @Output() actionSelected = new EventEmitter<string>();

  get surfaceContent(): A2UISurfaceContent {
    return this.activity.content as unknown as A2UISurfaceContent;
  }
}

// samples/commerce-agent-chat/react/src/components/ActivityRenderer.tsx
import type {ActivityMessage} from '@core/types/agent.js';
import type {A2UISurfaceContent} from '@core/types/commerce.js';
import {CommerceCatalogView} from './commerce/CommerceCatalogView.js';
import './ActivityRenderer.css';

interface ActivityRendererProps {
  activity: ActivityMessage;
  isLoading?: boolean;
  onActionSelected?: (prompt: string) => void;
}

export function ActivityRenderer({
  activity,
  isLoading = false,
  onActionSelected,
}: ActivityRendererProps): React.JSX.Element {
  if (activity.activityType === 'a2ui-surface') {
    return (
      <article className="activity-renderer" aria-label="Agent activity">
        <CommerceCatalogView
          content={activity.content as unknown as A2UISurfaceContent}
          isLoading={isLoading}
          onActionSelected={onActionSelected}
        />
      </article>
    );
  }

  return (
    <article className="activity-renderer" aria-label="Agent activity">
      <p className="activity-type">{activity.activityType}</p>
      <pre className="activity-content">
        {JSON.stringify(activity.content, null, 2)}
      </pre>
    </article>
  );
}
