// samples/commerce-agent-chat/vue/src/components/MessageInput.vue
<script setup lang="ts">
import {onMounted, onUnmounted, ref, watchEffect} from 'vue';

const props = defineProps<{
  disabled: boolean;
}>();

const emit = defineEmits<{
  send: [content: string];
}>();

interface MessageSendEvent extends CustomEvent<{content: string}> {}

interface MessageInputElement extends HTMLElement {
  disabled: boolean;
}

const elementRef = ref<MessageInputElement | null>(null);

watchEffect(() => {
  if (elementRef.value) {
    elementRef.value.disabled = props.disabled;
  }
});

function handleSend(event: Event) {
  emit('send', (event as MessageSendEvent).detail.content);
}

onMounted(() => {
  elementRef.value?.addEventListener('message-send', handleSend);
});

onUnmounted(() => {
  elementRef.value?.removeEventListener('message-send', handleSend);
});
</script>

<template>
  <cac-message-input ref="elementRef" />
</template>

// samples/commerce-agent-chat/react/src/components/MessageInput.tsx
import {useEffect, useRef} from 'react';

interface MessageSendEvent extends CustomEvent<{content: string}> {}

interface MessageInputProps {
  onSend: (message: string) => void;
  disabled: boolean;
}

interface MessageInputElement extends HTMLElement {
  disabled: boolean;
}

export function MessageInput({
  onSend,
  disabled,
}: MessageInputProps): React.JSX.Element {
  const elementRef = useRef<MessageInputElement | null>(null);

  useEffect(() => {
    if (elementRef.current) {
      elementRef.current.disabled = disabled;
    }
  }, [disabled]);

  useEffect(() => {
    const element = elementRef.current;
    if (!element) {
      return;
    }

    const handleSend = (event: Event) => {
      const customEvent = event as MessageSendEvent;
      onSend(customEvent.detail.content);
    };

    element.addEventListener('message-send', handleSend);
    return () => element.removeEventListener('message-send', handleSend);
  }, [onSend]);

  return <cac-message-input ref={elementRef} />;
}
