// samples/commerce-agent-chat/angular/src/app/components/message-input.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {FormsModule} from '@angular/forms';

@Component({
  selector: 'app-message-input',
  standalone: true,
  imports: [FormsModule],
  template: `
    <form
      class="message-form"
      (ngSubmit)="onSubmit()"
      aria-label="Send message"
    >
      <label for="chat-input" class="visually-hidden">Type your message</label>
      <p id="chat-input-hint" class="visually-hidden">
        Press Enter to send. Press Shift plus Enter to insert a new line.
      </p>
      <textarea
        id="chat-input"
        name="chatInput"
        class="message-input"
        [disabled]="disabled"
        [(ngModel)]="value"
        placeholder="Ask Zane..."
        rows="2"
        aria-describedby="chat-input-hint"
        (keydown)="onKeyDown($event)"
      ></textarea>
      <button
        type="submit"
        class="send-button"
        [disabled]="disabled || value.trim().length === 0"
      >
        Send
      </button>
    </form>
  `,
})
export class MessageInputComponent {
  @Input() disabled = false;
  @Output() send = new EventEmitter<string>();

  value = '';

  onKeyDown(event: KeyboardEvent): void {
    if (event.key !== 'Enter' || event.shiftKey) {
      return;
    }

    event.preventDefault();
    this.onSubmit();
  }

  onSubmit(): void {
    const content = this.value.trim();
    if (!content || this.disabled) {
      return;
    }

    this.send.emit(content);
    this.value = '';
  }
}

// samples/commerce-agent-chat/react/src/components/MessageInput.tsx
import {useState} from 'react';
import './MessageInput.css';

interface MessageInputProps {
  onSend: (message: string) => void;
  disabled: boolean;
}

export function MessageInput({
  onSend,
  disabled,
}: MessageInputProps): React.JSX.Element {
  const [input, setInput] = useState('');

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const next = input.trim();
    if (!next) {
      return;
    }

    onSend(next);
    setInput('');
  };

  const handleKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.key !== 'Enter' || event.shiftKey) {
      return;
    }

    event.preventDefault();

    const next = input.trim();
    if (!next || disabled) {
      return;
    }

    onSend(next);
    setInput('');
  };

  return (
    <form
      onSubmit={handleSubmit}
      className="message-input-form"
      aria-label="Send message"
    >
      <label className="visually-hidden" htmlFor="chat-input">
        Type your message
      </label>
      <p id="chat-input-hint" className="visually-hidden">
        Press Enter to send. Press Shift plus Enter to insert a new line.
      </p>
      <textarea
        id="chat-input"
        value={input}
        onChange={(event) => setInput(event.target.value)}
        onKeyDown={handleKeyDown}
        placeholder="Ask Zane..."
        disabled={disabled}
        className="message-input"
        rows={2}
        aria-describedby="chat-input-hint"
      />
      <button
        type="submit"
        disabled={disabled || input.trim().length === 0}
        className="send-button"
      >
        Send
      </button>
    </form>
  );
}
